name: Scraper 1-500
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SHARD_INDEX: 0
      SHARD_SIZE: 500
      CHECKPOINT_FILE: "checkpoint_0.txt"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install selenium webdriver-manager beautifulsoup4 gspread
      - name: Run Scraper
        run: python scraper.py
